title: Victoria Khaychuk # your name (or website title) here
logo: "/images/ml.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/in/victoria-khaychuk-b273ba3b/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-139577212-1 # your Google Analytics tracking ID here
